### PR TITLE
Fixed the :format respond_to issue

### PR DESCRIPTION
**Pull request by isterin**
The respond_to wasn't working with sinatra 1.1.2.  Setter on path_info must be set in order to modify route delayed method which is used by sinatra for routing.

### CODE REVIEW

**Comment by slowernet** [comment]
Would be great to get this merged into 0.6.1. Thanks for the patch, isterin.

**Comment by josb** [comment]
Please merge this change into 0.6.1. Thanks for the patch!

**Comment by isterin** [comment]
is this message for me?  Should i merge something, or are you just notifying the administrator?

**Comment by josb** [comment]
It was meant as a display of support for your patch, hopefully cehoffman will see it and pull your change.

**Comment by mpalmer** [comment]
I think cloudcrowd's patch (https://github.com/cloudcrowd/sinatra-respond_to/commit/e65de2a5a35d0e3efd8aae7f0e90da5b2c9bfdca) is cleaner.  I've tested it locally and it works well with sinatra 1.2.0.  It'd be nice if this was released ASAP; at present, it's very frustrating that the module doesn't appear to work right at _all_.

**Comment by cehoffman** [comment]
Integrated the fix, should have a new gem out today.

**Pull request closed without merging**
