### PR TITLE
Compatibility with Sinatra 1.3 (Second go)

### PR DESCRIPTION
**Pull request by smgt**

### CODE REVIEW

**Comment by slowernet** [comment]
+1

**Comment by mpalmer** [comment]
I had to apply this patch to make `sinatra-respond_to` work with Sinatra 1.3.1.  It'd be great if you could integrate this patch into a new release.

**Comment by joelash** [comment]
+1

**Comment by napcs** [comment]
+1

**Comment by mxriverlynn** [comment]
+1

**Pull request merged**
